version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - ./bulletin_board.env
    ports:
      - "9090:9090"
  postgres:
    image: "postgres:9.6-alpine"
#    ports:
#      - "6543:5432"